uploads = []
outputs = []

[[generated]]
id = "ZpJrQAdQu77RfgAnp21wr"
uri = "file://artifacts/kindnest/public/images/hero.png"
type = "image"
title = "Child and puppy hug"

[[generated]]
id = "vu-MKizOwRgBTBIbAjXP5"
uri = "file://artifacts/kindnest/public/images/cat.png"
type = "image"
title = "Rescue cat by window"

[[generated]]
id = "_PaOisQQ1evr5I9oGrMpp"
uri = "file://artifacts/kindnest/public/images/child.png"
type = "image"
title = "Child drawing with crayons"

[[generated]]
id = "eWBLfRJdelQ3V1upa7VeK"
uri = "file://artifacts/kindnest/public/images/community.png"
type = "image"
title = "Diverse community outdoors"
